ruby/Ruby on Rails/zombie_twitter/config/routes.rb
ZombieTwitter < Application.routes.draw do
	resources :tweets
	root to: "tweets#index"
	get '/new_tweet' => 'tweets#new'
	get '/all' => 'tweets#index', as 'all_tweets'
	get '/all' => redirect('/tweets')
	get '/local_tweets/:zipcode' => 'tweets#index', as 'local_tweets'
	get ':name' => 'tweets#index', as 'zombie_tweets '
end

ruby/Ruby on Rails/zombie_twitter/app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :zombie
	validates :status,
				presence: true,
				length: { minimum: 3 }
end

class Zombie < ActiveRecord::Base
	has_many :tweets
end

ruby/Ruby on Rails/zombie_twitter/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_action :get_tweet, only: [:edit,:update,:destroy]
	before_action :check_auth, :only => [:edit,:update,:destroy]

	def get_tweet
		@tweet = Tweet.find(params[:id])
	end

	def check_auth
		if session[:zombie_id] != @tweet.zombie_id
			flash:[notice] = "Sorry, you can't edit this tweet"
			redirect_to(tweets_path)
		end
	end
	def index
		if params[:name]
			@zombie = Zombie.where(name: params[:name]).first
			@tweets = @zombie.tweets
		else
			@tweets = Tweet.all
		if params[:zipcode]
			@tweets = Tweet.where(zipcode: params[:zipcode])
		else
			@tweets = Tweet.all
		end
		respond_to do |format|
			format.html # index.html.erb
			format.xml {render xml: @tweets}
		end
	end

	def show
		render action: 'status'
	end

	def new
		
	end

	def edit

	end

	def create
		
	end

	def update
		
	end

	def destroy
		
	end
end

ruby/Ruby on Rails/zombie_twitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Rails for Zombies</title>
</head>
<body>
<div id="codeschool">
	<a href="https://www.codeschool.com" id="codeschool-logo" rel="internal">Code School</a>
	<ul>
		<li><a href="https://www.codeschool.com" rel="internal">Home</a></li>
		<li><a href="https://www.codeschool.com/code_tv" rel="internal">Code TV</a></li>
		<li><a href="https://www.codeschool.com/account" rel="internal">My Account</a></li>
		<li><a href="https://www.codeschool.com/support" rel="internal">Support</a></li>
	</ul>
	<a href="/users/sign_out" id="codeschool-session" rel="internal">Sign Out</a>
	<a href="https://www.codeschool.com/account" id="codeschool-user" rel="internal">Alexandre Carretero (Alex)</a>
	<h2 id="sidebar-points"></h2>
</div>
<% if flash[:notice] %>
	<div><%= flash[:notice] %></div>
<% end %>

<%= yield %>

</body>
</html>

ruby/Ruby on Rails/zombie_twitter/app/views/tweets/index.html.erb
<h1>Listing Tweets</h1>
<table>
	<tr>
		<th>Status</th>
		<th>Zimbie</th>
	</tr>
<% tweets = Tweet.all %>
<% tweets.all.each do |tweet| %>
	<tr>
		<td><%= link_to tweet.status, tweet %></td>
		<td><%= link_to tweet.zombie.name, tweet.zombie %></td>
		<td><%= link_to "Edit", edit_tweet_path(tweet) %></td>
		<td><%= link_to "Destroy", tweet, method: :delete %></td>
	</tr>
<% end %>
<% if tweets.size == 0 %>
	<em>No Tweets Found</em>
<% end %>
</table>

ruby/Ruby on Rails/zombie_twitter/app/views/tweets/show.html.erb
<h1><%= @tweet.status %></h1>
<p>Posted by: <%= link_to @tweet.zombie.name, @tweet.zombie, confirm: "Are you sure?" %></p>